### PR TITLE
Initial 1.13 update

### PR DESCRIPTION
**Pull request by nnooney**
This branch prepares Minutor for parsing files generated in Minecraft 1.13. Notably, it contains the following changes:
- Addition of New NBT Tag "Tag_Long_Array"
- Updates to chunk.cpp to parse new chunk format
- Begin flattening of vanilla_ids.json
- Update mapview.cpp to remove "data" tag
- Update blockidentifier to search based upon block name

I've tested these changes on my world which was generated in 1.13-pre10. The vanilla_ids.json still needs more work, as well as the mapview and blockidentifier, but this should be a start for those who want to look at their maps in the new 1.13 format.

### CODE REVIEW

**Comment by nnooney** [comment]
This pull request should help with #125

**Comment by erich666** [comment]
I have nothing important to add, other than to say you're my personal hero for the week. I'm just about to start on this task for Mineways (which has diverged significantly from minutor at this point), and I suspect your explorations here will save me many hours. I'll try to post whatever new info I find here (unless you beat me to it).

**Comment by nnooney** [comment]
With the update to the vanilla ids, I was able to remove most of the remaining unknown blocks for world rendering. Here is a comparison of worlds from 1.12 and 1.13:

divenon_1-12 copy

divenon_1_13 copy

These images are compressed so they will fit on GitHub, but it is interesting to see an overview of how they differ. I haven't updated the biomes file yet to add different variants for water, but that should be doable. I also noticed that the naming is wrong for `light_gray_terracotta`, so I can also fix that.



Also, here is a view of coral reefs rendered at layer 60 of this world:

world_1-13_layer60

**Comment by nnooney** [comment]
I've now added the ocean biomes (and other 1.13 biomes) to vanilla_biomes.json. The oceans now have a subtle effect on the water color.

biome ocean

The colder temperatures have a darker tint applied to them to give the appearance that the water is colder. The settings could be adjusted to find the right effect; I just tinkered with them until it looked reasonable.

**Comment by nnooney** [comment]
This is not backwards compatible. I had to make significant changes to the Definition Manager and Block Identifier in order to support the transition from block ids to names. I would suggest making this a separate release and continue to have the 1.12x branch available for the time being.

**Comment by EtlamGit** [comment]
Your 1.12 image is created with an old version of Minutor. Biome depending Grass colors are missing, but are used for the 1.13 image.

**Comment by EtlamGit** [comment]
@nnooney where did you find the values for watermodifier for the different ocean types?

**Comment by nnooney** [comment]
I made up the water modifier values until I found something that I liked. They run in a gradient from blue (results in no change in color) to red (makes the water a darker color). I ordered the oceans from what I thought was warmest to coldest:

- Warm Ocean
- Deep Warm Ocean
- Lukewarm Ocean
- Deep Lukewarm Ocean
- Ocean
- Deep Ocean
- Cold Ocean
- Deep Cold Ocean
- Frozen Ocean
- Deep Frozen Ocean

These numbers can definitely be modified (I was initially hoping for a way to make the warm oceans a lighter color than the default).

**Comment by nnooney** [comment]
The 1.12 image was created from the latest download available on the website, which is why it seems there is so much difference.

**Comment by EtlamGit** [comment]
Aha, good to know with the water colors. The swamp watermodifier is origin directly from Minecraft source code. And as Mojang also seems to modify water color across the new ocean biomes I would like to test the color values they use in the code.
But that can wait some month...

**Comment by nnooney** [comment]
I agree that using the Minecraft provided values would be the end goal here. I wonder if those values are encoded in the new biome data. I've been focusing mostly on rendering the blocks, so sometime in the future I'll take a look at where those values come from.

**Pull request closed without merging**
