### PR TITLE
Removed zoom factor from keyboard movement and did some code clean-up (#109)

### PR DESCRIPTION
**Pull request by Metibor**
I think the zoom factor is not needed.
Also the type of stepSize was wrong before. Without the factor an int should be correct.

### CODE REVIEW

**Comment by mrkite** [comment]
I'm not going to merge this just yet because I need to test something.  The zoom factor is there so that the map moves the same amount regardless of zoom.  If you zoom fully in, pressing the left arrow will scroll the map by (completely made up number) 30 pixels, when you zoom fully out, it still moves the map by 30 pixels.

If you zoom completely out and use the arrow keys, the map would pan excrutiatingly slow otherwise.

**Comment by Metibor** [comment]
By removing the factor, I wanted to switch from pixel based movement to block based movement.

**Current situation (stepSize / zoom)**
Normal zoom (1 block is displayed as 1 pixel):
If I press the an arrow key once, the map moves 16 pixels which is 16 blocks.
Zoomed in (i.e. 1 block is displayed as 4 pixels):
If I press the an arrow key once, the map moves 16 pixels which is only 4 blocks.

=> So the movement is pixel-based

**Proposed (just stepSize)**
Normal zoom (1 block is displayed as 1 pixel):
If I press the an arrow key once, the map moves 16 pixels which is 16 blocks.
Zoomed in (i.e. 1 block is displayed as 4 pixels):
If I press the an arrow key once, the map moves 64 pixels which is still 16 blocks.

=> Now the movement is block-based

I think that this is more intuitive, but I have to admit the following:
If you zoom close to the map (i.e. factor 16) and make bigger steps (i.e. Alt+Arrow) the movement is really big (16 * 128) and you can't see where you are going anymore.

Maybe I can make it an option in the settings screen and use the old as default...

**Comment by EtlamGit** [comment]
What about:
- moving pixel based and with zoom factor when no modifier keys are pressed
- move block/chunk/region based when the corresponding modifier key is pressed

I think it is also useful, to get the left-top pixel aligned to the block/chunk/region I am moving in that moment. Meaning, no half chunks at left and top border.

**Comment by Metibor** [comment]
Hi, I readded the zoom factor, so the only change in this pull request is changing my int to float.

The half-pixel-problem exists in both versions, but with the pixel based movement (with the factor) it is easier to remove them (Shift+Arrow).

**Comment by Metibor** [comment]
Oh, you said half-chunks. You can't see them currently, because there is no real indicator for that. Maybe we could add an overlay for chunk/region borders?

**Comment by EtlamGit** [comment]
We have an overlay for them already, but also only via [command line](https://github.com/mrkite/minutor/wiki/Command-Line) ...
(I use them during automatic map export.)

My suggestion was just to align the left-topmost pixel of the map to a chunk/region when in special keyboard navigation mode. That would make it easier to do screen shots or plan chunk-border dependent builds.
But you are right, adding an control element in the GUI to toggle this feature is something I could do also.

**Comment by Metibor** [comment]
Please, could you merge my changes from April 14th, or are there some problems left?
The current navigation is based on the center pixel. Changing that, should be another issue.

**Comment by mrkite** [comment]
Yeah, sorry about that.

**Pull request merged**
