### PR TITLE
Implementation of a "Location" window requested in #110

### PR DESCRIPTION
**Pull request by Metibor**
Hi there,
I finished my vision of the feature I requested in #110.
Please do a code review before considering a merge. I am more of a Java programmer and don't know very much about the pointer stuff in C/C++. There could be some really derpy mistakes. :-)
Also, try it out and give me some feedback about the usability or other things!

### CODE REVIEW

**Comment by mrkite** [comment]
Can you rebase those into one commit?

**Comment by Metibor** [comment]
Git-Noob asking:
I am pretty sure that this is possible, but may I ask why this should be done?
Is there a special reason for that? Because you can see the complete diff if you select "Files changed" on the top of this page.
Or is there a way to do it without destroying my commit history?
Maybe I could merge my jumpto branch into my master branch and submit that as a pull request? Would that work?

**Comment by madmaxoft** [comment]
Usually rebase-squashing is done so that when you later look into the history, the change is presented as a single commit, and there are no "fixed previous build failure", "fixed a forgotten XY" and similar commits. Since this is logically a single change, it deserves a single commit.

As for how to do it, using commandline:
```
(if not added yet: )
git remote add https://github.com/mrkite/minutor upstream
git fetch upstream
git rebase -i upstream/master
(in the interactive rebase, choose to keep the first commit and then fixup for all the other commits)
```

**Comment by Metibor** [comment]
OK, I will look into it, but it may take some time, because I want to know what I do, before I do it.
So the question is:
Will the steps above keep all the commits in my local repository or will they also be squashed?
For now I would like to keep the small steps including the description, because I am still in the learning process and working all those things out.

Oh and another question is: I have to do the steps in my jumpto branch, right?

**Comment by mrkite** [comment]
It will squash them in your local repo.  So you may want to do a local branch if you want to keep them, and just squash them in master.

You have a bunch of slots for the spinboxes that don't seem to actually be connected to the spinbox signals..  I don't believe they're necessary anyway.

**Comment by Metibor** [comment]
I will make a new pull request.

**Comment by madmaxoft** [comment]
@mrkite You know that Github can squash-rebase-merge PRs, right?

**Comment by mrkite** [comment]
@madmaxoft no, I didn't realize that.  I guess that's under the advanced manual merge and not the automatic merge :)

**Pull request closed without merging**
